[Core]
Address = "127.0.0.1"
Port = 1337
Graceful = 15 # Request timeout in minutes
RootPath = "/api/v1"
DBString = "file:./runtime/chars.db?cache=shared&mode=rwc&_fk=1" # file:ent?cache=shared&mode=memory&_fk=1

[RateLimit]
Enable = false
MaxRequests = 500 # Max amount of requests in time range of MaxAge
MaxAge = 1 # Max age of ratelimiter bucket in minutes

[Cert]
Enable = false
Domain = ""

[ApiAuth]
EnforceKey = false # Enforce game servers to use API key
EnforceIP = false # Enforce IP whitelist
Key = "" # API key
IPListFile = "./runtime/ipwhitelist.json" 

[Verify]
EnforceMap = false # Enforce map hash check
EnforceBan = false # Enforce player "FN" bans
EnforceSC = false
MapListFile = "./runtime/game/maps.json"
BanListFile = "./runtime/game/bans.json"
AdminListFile = "./runtime/game/admins.json"
SCHash = 125454

[Log]
Level = "debug"
Dir = "./runtime/logs/" # Where should we keep the bot log file.
ExpireTime = "24h"
