core:
  address: 127.0.0.1
  port: 1337
  timeout: 60
  dbtype: ""
database:
  mongodb:
    connection: ""
  bbolt:
    file: ""
    timeout: 0
ratelimit:
  maxrequests: 0 # Max amount of requests in time range of MaxAge
  maxage: "" # Max age of ratelimiter bucket in minutes
cert:
  enable: false
  domain: ""
apiauth:
  systemadmins: ./runtime/systemadmins.json
  iplistfile: ./runtime/ipwhitelist.json
  enforcekey: false
  enforceip: false
  useragent: ""
verify:
  enforceban: false
  enforcemap: false
  enforcebins: false
  maplistfile: ./runtime/game/maps.json
  banlistfile: ./runtime/game/bans.json
  adminlistfile: ./runtime/game/admins.json
  serverunixbin: ./runtime/game/ms.dll
  serverwinbin: ./runtime/game/ms.so
  scriptsbin: ./runtime/game/sc.dll
char:
  maxbackups: 10
  backuptime: 1h
log:
  level: debug
  dir: ./runtime/logs/ # Where should we keep the bot log files.
  expiretime: 24h