[Core]
Port = 1337
IP = "127.0.0.1"
Graceful = 15 # Request timeout in minutes
RootPath = "/api/v1"
DBString = "./runtime/characters.db" # file:ent?mode=memory&cache=shared&_fk=1

[RateLimit]
Enable = false
MaxRequests = 500 # Max amount of requests in time range of MaxAge
MaxAge = 1 # Max age of ratelimiter bucket in minutes

[TLS]
Enable = false
Port = 1337
CertFile = ""
KeyFile = ""

[ApiAuth]
EnforceKey = false # Enforce game servers to use API key
EnforceIP = false # Enforce IP whitelist
Key = "" # API key
IPListFile = "./runtime/ipwhitelist.json" 

[Verify]
EnforceMap = false # Enforce map hash check
EnforceBan = false # Enforce player "FN" bans
EnforceSC = false
MapListFile = "./runtime/game/maps.json"
BanListFile = "./runtime/game/bans.json"
SCHash = 125454

[Log]
Dir = "./runtime/logs/" # Where should we keep the bot log file.
