// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/msrevive/nexus2/internal/ent/deprecatedcharacter"
)

// DeprecatedCharacter is the model entity for the DeprecatedCharacter schema.
type DeprecatedCharacter struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Steamid holds the value of the "steamid" field.
	Steamid string `json:"steamid,omitempty"`
	// Slot holds the value of the "slot" field.
	Slot int `json:"slot"`
	// Size holds the value of the "size" field.
	Size int `json:"size,omitempty"`
	// Data holds the value of the "data" field.
	Data string `json:"data,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeprecatedCharacter) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case deprecatedcharacter.FieldSlot, deprecatedcharacter.FieldSize:
			values[i] = new(sql.NullInt64)
		case deprecatedcharacter.FieldSteamid, deprecatedcharacter.FieldData:
			values[i] = new(sql.NullString)
		case deprecatedcharacter.FieldID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type DeprecatedCharacter", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeprecatedCharacter fields.
func (dc *DeprecatedCharacter) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deprecatedcharacter.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				dc.ID = *value
			}
		case deprecatedcharacter.FieldSteamid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field steamid", values[i])
			} else if value.Valid {
				dc.Steamid = value.String
			}
		case deprecatedcharacter.FieldSlot:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field slot", values[i])
			} else if value.Valid {
				dc.Slot = int(value.Int64)
			}
		case deprecatedcharacter.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				dc.Size = int(value.Int64)
			}
		case deprecatedcharacter.FieldData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value.Valid {
				dc.Data = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this DeprecatedCharacter.
// Note that you need to call DeprecatedCharacter.Unwrap() before calling this method if this DeprecatedCharacter
// was returned from a transaction, and the transaction was committed or rolled back.
func (dc *DeprecatedCharacter) Update() *DeprecatedCharacterUpdateOne {
	return (&DeprecatedCharacterClient{config: dc.config}).UpdateOne(dc)
}

// Unwrap unwraps the DeprecatedCharacter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dc *DeprecatedCharacter) Unwrap() *DeprecatedCharacter {
	tx, ok := dc.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeprecatedCharacter is not a transactional entity")
	}
	dc.config.driver = tx.drv
	return dc
}

// String implements the fmt.Stringer.
func (dc *DeprecatedCharacter) String() string {
	var builder strings.Builder
	builder.WriteString("DeprecatedCharacter(")
	builder.WriteString(fmt.Sprintf("id=%v", dc.ID))
	builder.WriteString(", steamid=")
	builder.WriteString(dc.Steamid)
	builder.WriteString(", slot=")
	builder.WriteString(fmt.Sprintf("%v", dc.Slot))
	builder.WriteString(", size=")
	builder.WriteString(fmt.Sprintf("%v", dc.Size))
	builder.WriteString(", data=")
	builder.WriteString(dc.Data)
	builder.WriteByte(')')
	return builder.String()
}

// DeprecatedCharacters is a parsable slice of DeprecatedCharacter.
type DeprecatedCharacters []*DeprecatedCharacter

func (dc DeprecatedCharacters) config(cfg config) {
	for _i := range dc {
		dc[_i].config = cfg
	}
}
