// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CharactersColumns holds the columns for the "characters" table.
	CharactersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "steamid", Type: field.TypeString},
		{Name: "slot", Type: field.TypeInt},
		{Name: "size", Type: field.TypeInt, Default: 0},
		{Name: "data", Type: field.TypeString, SchemaType: map[string]string{"sqlite3": "text"}},
	}
	// CharactersTable holds the schema information for the "characters" table.
	CharactersTable = &schema.Table{
		Name:       "characters",
		Columns:    CharactersColumns,
		PrimaryKey: []*schema.Column{CharactersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "character_id",
				Unique:  true,
				Columns: []*schema.Column{CharactersColumns[0]},
			},
			{
				Name:    "character_steamid_slot",
				Unique:  false,
				Columns: []*schema.Column{CharactersColumns[1], CharactersColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CharactersTable,
	}
)

func init() {
}
