// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/msrevive/nexus2/ent/deprecatedcharacter"
)

// DeprecatedCharacterCreate is the builder for creating a DeprecatedCharacter entity.
type DeprecatedCharacterCreate struct {
	config
	mutation *DeprecatedCharacterMutation
	hooks    []Hook
}

// SetSteamid sets the "steamid" field.
func (dcc *DeprecatedCharacterCreate) SetSteamid(s string) *DeprecatedCharacterCreate {
	dcc.mutation.SetSteamid(s)
	return dcc
}

// SetSlot sets the "slot" field.
func (dcc *DeprecatedCharacterCreate) SetSlot(i int) *DeprecatedCharacterCreate {
	dcc.mutation.SetSlot(i)
	return dcc
}

// SetNillableSlot sets the "slot" field if the given value is not nil.
func (dcc *DeprecatedCharacterCreate) SetNillableSlot(i *int) *DeprecatedCharacterCreate {
	if i != nil {
		dcc.SetSlot(*i)
	}
	return dcc
}

// SetSize sets the "size" field.
func (dcc *DeprecatedCharacterCreate) SetSize(i int) *DeprecatedCharacterCreate {
	dcc.mutation.SetSize(i)
	return dcc
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (dcc *DeprecatedCharacterCreate) SetNillableSize(i *int) *DeprecatedCharacterCreate {
	if i != nil {
		dcc.SetSize(*i)
	}
	return dcc
}

// SetData sets the "data" field.
func (dcc *DeprecatedCharacterCreate) SetData(s string) *DeprecatedCharacterCreate {
	dcc.mutation.SetData(s)
	return dcc
}

// SetID sets the "id" field.
func (dcc *DeprecatedCharacterCreate) SetID(u uuid.UUID) *DeprecatedCharacterCreate {
	dcc.mutation.SetID(u)
	return dcc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dcc *DeprecatedCharacterCreate) SetNillableID(u *uuid.UUID) *DeprecatedCharacterCreate {
	if u != nil {
		dcc.SetID(*u)
	}
	return dcc
}

// Mutation returns the DeprecatedCharacterMutation object of the builder.
func (dcc *DeprecatedCharacterCreate) Mutation() *DeprecatedCharacterMutation {
	return dcc.mutation
}

// Save creates the DeprecatedCharacter in the database.
func (dcc *DeprecatedCharacterCreate) Save(ctx context.Context) (*DeprecatedCharacter, error) {
	var (
		err  error
		node *DeprecatedCharacter
	)
	dcc.defaults()
	if len(dcc.hooks) == 0 {
		if err = dcc.check(); err != nil {
			return nil, err
		}
		node, err = dcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeprecatedCharacterMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = dcc.check(); err != nil {
				return nil, err
			}
			dcc.mutation = mutation
			if node, err = dcc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(dcc.hooks) - 1; i >= 0; i-- {
			if dcc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dcc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dcc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dcc *DeprecatedCharacterCreate) SaveX(ctx context.Context) *DeprecatedCharacter {
	v, err := dcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcc *DeprecatedCharacterCreate) Exec(ctx context.Context) error {
	_, err := dcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcc *DeprecatedCharacterCreate) ExecX(ctx context.Context) {
	if err := dcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dcc *DeprecatedCharacterCreate) defaults() {
	if _, ok := dcc.mutation.Slot(); !ok {
		v := deprecatedcharacter.DefaultSlot
		dcc.mutation.SetSlot(v)
	}
	if _, ok := dcc.mutation.Size(); !ok {
		v := deprecatedcharacter.DefaultSize
		dcc.mutation.SetSize(v)
	}
	if _, ok := dcc.mutation.ID(); !ok {
		v := deprecatedcharacter.DefaultID()
		dcc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dcc *DeprecatedCharacterCreate) check() error {
	if _, ok := dcc.mutation.Steamid(); !ok {
		return &ValidationError{Name: "steamid", err: errors.New(`ent: missing required field "DeprecatedCharacter.steamid"`)}
	}
	if _, ok := dcc.mutation.Slot(); !ok {
		return &ValidationError{Name: "slot", err: errors.New(`ent: missing required field "DeprecatedCharacter.slot"`)}
	}
	if v, ok := dcc.mutation.Slot(); ok {
		if err := deprecatedcharacter.SlotValidator(v); err != nil {
			return &ValidationError{Name: "slot", err: fmt.Errorf(`ent: validator failed for field "DeprecatedCharacter.slot": %w`, err)}
		}
	}
	if _, ok := dcc.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "DeprecatedCharacter.size"`)}
	}
	if _, ok := dcc.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "DeprecatedCharacter.data"`)}
	}
	return nil
}

func (dcc *DeprecatedCharacterCreate) sqlSave(ctx context.Context) (*DeprecatedCharacter, error) {
	_node, _spec := dcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (dcc *DeprecatedCharacterCreate) createSpec() (*DeprecatedCharacter, *sqlgraph.CreateSpec) {
	var (
		_node = &DeprecatedCharacter{config: dcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: deprecatedcharacter.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: deprecatedcharacter.FieldID,
			},
		}
	)
	if id, ok := dcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dcc.mutation.Steamid(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: deprecatedcharacter.FieldSteamid,
		})
		_node.Steamid = value
	}
	if value, ok := dcc.mutation.Slot(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: deprecatedcharacter.FieldSlot,
		})
		_node.Slot = value
	}
	if value, ok := dcc.mutation.Size(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: deprecatedcharacter.FieldSize,
		})
		_node.Size = value
	}
	if value, ok := dcc.mutation.Data(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: deprecatedcharacter.FieldData,
		})
		_node.Data = value
	}
	return _node, _spec
}

// DeprecatedCharacterCreateBulk is the builder for creating many DeprecatedCharacter entities in bulk.
type DeprecatedCharacterCreateBulk struct {
	config
	builders []*DeprecatedCharacterCreate
}

// Save creates the DeprecatedCharacter entities in the database.
func (dccb *DeprecatedCharacterCreateBulk) Save(ctx context.Context) ([]*DeprecatedCharacter, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dccb.builders))
	nodes := make([]*DeprecatedCharacter, len(dccb.builders))
	mutators := make([]Mutator, len(dccb.builders))
	for i := range dccb.builders {
		func(i int, root context.Context) {
			builder := dccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeprecatedCharacterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dccb *DeprecatedCharacterCreateBulk) SaveX(ctx context.Context) []*DeprecatedCharacter {
	v, err := dccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dccb *DeprecatedCharacterCreateBulk) Exec(ctx context.Context) error {
	_, err := dccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dccb *DeprecatedCharacterCreateBulk) ExecX(ctx context.Context) {
	if err := dccb.Exec(ctx); err != nil {
		panic(err)
	}
}
