name: build

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: get build tools
        run: sudo apt-get -y install build-essential

      - name: build
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o build/msnexus2_linux_amd64 -v .

      - name: compress binary
        run: upx build/msnexus2_linux_amd64 && chmod +x build/msnexus2_linux_amd64

      - name: upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: linux_amd64
          path: build/msnexus2_linux_amd64