name: build-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: run
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go run -ldflags="-s -w" -v .