name: linux-build
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: get build tools
        run: sudo apt-get -y install build-essential

      - name: build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o build/nexus2_linux_amd64 -v .

      - name: compress binary
        run: upx build/nexus2_linux_amd64 && chmod +x build/nexus2_linux_amd64

      - name: upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: linux_amd64
          path: build/nexus2_linux_amd64