name: create release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: get build tools
        run: sudo apt-get -y install build-essential
      - name: build
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o build/msnexus2_linux_amd64 -v .
      - name: compress binary
        run: upx build/msnexus2_linux_amd64 && chmod +x build/msnexus2_linux_amd64
      - name: copy runtime directory
        run: cp -avr ./runtime/ ./build/
      - name: tar release
        run: tar -czvf ~/msnexus2.tar.gz build
      - name: extract changelog
        env:
          REF: ${{ github.ref }}
        run: sed -n "/^## ${REF:10}/,/^## /{/^## /b;p}" CHANGELOG.md > ./RELEASE_CHANGELOG
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: ./RELEASE_CHANGELOG
          draft: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'rc') }}
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/msnexus2.tar.gz
          asset_name: msnexus2.tar.gz
          asset_content_type: application/octet-stream