name: test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.22'

      - name: get build tools
        run: sudo apt-get -y install build-essential
      
      - name: test build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
      #- name: test
        #run: GOFLAGS="-count=1" go test -race -covermode=atomic ./...
