name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - name: get build tools
        run: sudo apt-get -y install build-essential
      - name: test
        run: GOFLAGS="-count=1" go test -race -covermode=atomic ./...
