// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Character is the predicate function for character builders.
type Character func(*sql.Selector)

// DeprecatedCharacter is the predicate function for deprecatedcharacter builders.
type DeprecatedCharacter func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)
